apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: "secret-inject"
  name: "secret-inject"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      run: "secret-inject"
  template:
    metadata:
      labels:
        run : "secret-inject"
    spec:
      volumes:
        - name: certs
          secret:
            secretName: "secret-inject-tls"
      containers:
        - name: "secret-inject-init"
          image: "664393803520.dkr.ecr.us-east-1.amazonaws.com/aws-secrets-manager-secret-adm-controller:latest"
          volumeMounts:
            - name: certs
              mountPath: /tls
              readOnly: true
          args:
          - "--tls-cert-file=/tls/tls.crt"
          - "--tls-private-key-file=/tls/tls.key"
          - "--sidecar-image=664393803520.dkr.ecr.us-east-1.amazonaws.com/aws-secrets-manager-secret-sidecar:latest"
          ports:
          - containerPort: 443
          imagePullPolicy: Always
